Check test-container
Signed-off-by: Daniel Metzner <daniel.metzner@niceshops.com>

diff --git a/.github/workflows/container_tests.yaml b/.github/workflows/container_tests.yaml
--- a/.github/workflows/container_tests.yaml
+++ b/.github/workflows/container_tests.yaml
@@ -65,7 +65,12 @@ jobs:
       - name: Run a few dynamic software tests
         run: |
           docker exec app.catroweb chmod -R 777 var
-          docker exec app.catroweb bin/behat -s web-general tests/BehatFeatures/web/general/homepage.feature
+          if ! docker exec app.catroweb bin/behat -s web-general tests/BehatFeatures/web/general/homepage.feature; then
+            echo "Initial run failed. Rerunning failed scenarios..."
+            docker exec app.catroweb bin/behat -s web-general --rerun
+          else
+            echo "Initial run passed. No rerun needed."
+          fi
 
       - name: Test shared volumes, by expecting a crash with invalid changes to the test file
         id: shared-test-run-must-fail
